apps/front/models.py
from datetime import datetime

from exts import db
from werkzeug.security import check_password_hash, generate_password_hash
import shortuuid
import enum


class GenderEnum(enum.Enum):
    MALE = '男'
    FEMALE = '女'
    UNKNOW = '未知'


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(50), primary_key=True, default=shortuuid.uuid)
    # phone = db.Column(db.String(11), unique=True)
    username = db.Column(db.String(50), nullable=False, unique=True)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    # realname = db.Column(db.String(50))
    qq = db.Column(db.String(10))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    avatar = db.Column(db.String(50))
    signature = db.Column(db.String(100))

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = generate_password_hash(password)

    def check_password(self, raw_pwd):
        return check_password_hash(self.password, raw_pwd)

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(FrontUser, self).__init__(*args, **kwargs)


class BoardManage(db.Model):
    __tablename__ = 'board_manager'
    id = db.Column(db.Integer, primary_key=True)
    manager_id = db.Column(db.String(100), db.ForeignKey('front_user.id'), nullable=False)
    board_id = db.Column(db.Integer, db.ForeignKey('board.id'), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)

    board = db.relationship('Board', backref=db.backref('board_managers', cascade='all'))
    manager = db.relationship('FrontUser', backref=db.backref('boards_managing', cascade='all'))


class ThreadBrowseLogs(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    thread_id = db.Column(db.Integer, db.ForeignKey('thread.id', ondelete='CASCADE'))
    request_ip = db.Column(db.String(15), nullable=True)
    user_id = db.Column(db.String(50), nullable=True)
    ua = db.Column(db.String(50), nullable=True)
    create_time = db.Column(db.DateTime, default=datetime.now)

apps/front/forms.py
from wtforms import Form, StringField, IntegerField
from wtforms.validators import Regexp, InputRequired, EqualTo, ValidationError, Email, Length
from exts import cache
from apps.forms import BaseForm
import hashlib


class SendSMSForm(Form):
    salt = 'fdjfjdjgdgd5g4f4d5'
    phone = StringField(validators=[Regexp(r'^1[3456789]\d{9}$')])
    timestamp = StringField(validators=[Regexp(r'\d{13}')])
    sign = StringField(validators=[InputRequired()])

    def validate(self):
        if not super(SendSMSForm, self).validate():
            return False
        phone = self.phone.data
        timestamp = self.timestamp.data
        sign = self.sign.data
        encry_sign = hashlib.md5((phone + timestamp + self.salt).encode('utf-8')).hexdigest()
        if sign == encry_sign:
            return True
        else:
            return False


class RegisterForm(BaseForm):
    email = StringField(validators=[Email('请输入正确格式的邮箱')])
    captcha = StringField(validators=[InputRequired(message='请输入6位邮箱验证码')])
    username = StringField(validators=[Regexp(r'^.{2,10}$', message='请输入2-10位长度的用户名')])
    password1 = StringField(validators=[Regexp(r'^[a-zA-Z0-9_-]{6,20}$', message='请输入6-20位正确格式的密码')])
    password2 = StringField(validators=[EqualTo('password1')])
    img_captcha = StringField(validators=[Regexp(r'[a-zA-Z0-9]{4}', message='请输入4位图形验证码')])

    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        phone = self.phone.data
        captcha = cache.get(phone)
        if not captcha or captcha.lower() != sms_captcha.lower():
            raise ValidationError('短信验证码不正确')

    def validate_img_captcha(self, field):
        img_captcha = field.data
        if not img_captcha:
            raise ValidationError('请输入正确的图形验证码')


class LoginForm(BaseForm):
    account = StringField(validators=[InputRequired(message='请输入用户名或邮箱')])
    password = StringField(validators=[Regexp(r'^[a-zA-Z0-9_-]{6,20}$', message='请输入6-20位的密码')])
    remember = StringField()


class ThreadForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入帖子标题')])
    content = StringField(validators=[InputRequired(message='请输入帖子内容')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块ID')])


class CommentForm(BaseForm):
    content = StringField(validators=[InputRequired('请输入评论内容')])
    author_id = StringField(validators=[InputRequired('请输入作者ID')])
    thread_id = IntegerField(validators=[InputRequired('请输入帖子ID')])


class ChildCommentForm(CommentForm):
    parent_id = IntegerField(validators=[InputRequired('请输入父评论ID')])


class UpdateProfileForm(BaseForm):
    username = StringField(validators=[Regexp(r'^.{2,10}$', message='请输入正确格式的用户名')])
    email = StringField(validators=[Email('请输入正确格式的邮箱')])
    # phone = StringField(validators=[Regexp(r'^1[3456789]\d{9}$', message='请输入正确格式的手机号！')])
    # qq = StringField(validators=[Regexp(r'[123456789]\d{4,9}', message='请输入正确格式的QQ号！')])
    # gender = StringField(validators=[Regexp(r'[男女(未知)]')])

apps/common/views.py
from flask import Blueprint, make_response, request, render_template, jsonify, send_from_directory
from utils.captcha import Captcha
from io import BytesIO
from utils.sms import send_sms
from utils import restful
from exts import cache
from apps.front.forms import SendSMSForm
from werkzeug.utils import secure_filename
import string
import random
import config
import os

bp = Blueprint('common', __name__)


@bp.route('/captcha/')
def captcha():
    text, image = Captcha.gene_graph_captcha()
    text = text.lower()
    io = BytesIO()
    image.save(io, 'png')
    io.seek(0)
    resp = make_response(io.read())
    resp.content_type = 'image/png'
    cache.set(text, text, timeout=90)
    # print(text)
    return resp


@bp.route('/verify_captcha/<code>/')
def verify_captcha(code):
    # code = request.args.get('code')
    code = code.lower()
    flag = True if cache.get(code) else False
    return jsonify({'code': 200, 'verified': flag})


@bp.route('/sms_captcha/', methods=["POST"])
def sms_captcha():
    form = SendSMSForm(request.form)
    if form.validate():
        phone = form.phone.data
        captcha = "".join(random.sample(list(string.digits), 6))
        try:
            send_sms(phone, captcha)
            cache.set(phone, captcha)
            print(captcha)
            return restful.success('发送验证码成功')
        except:
            resp = send_sms(phone, captcha)
            print(captcha)
            return restful.server_error(resp['msg'])
    else:
        return restful.params_error(form.get_error())


@bp.route('/upload/', methods=['get', 'post'])
def upload():
    if request.method == 'GET':
        return render_template('common/upload.html')
    if not os.path.dirname(config.UPLOAD_FOLDER):
        os.mkdir(config.UPLOAD_FOLDER)
    f = request.files.get('myfile')
    if not f:
        return jsonify({'code': 400, 'message': 'no file'})
    filename = secure_filename(f.filename)
    filepath = os.path.join(config.UPLOAD_FOLDER, filename)
    f.save(filepath)
    return jsonify({'code': 200, 'message': 'upload successfully'})


@bp.route('/download/<path:filename>/')
def download(filename):
    filedir = config.UPLOAD_FOLDER
    return send_from_directory(filedir, filename, as_attachment=True)


@bp.route('/filelist/')
def filelist():
    files = {}
    for file in os.listdir(config.UPLOAD_FOLDER):
        fullpath = os.path.join(config.UPLOAD_FOLDER, file)
        size = round(os.path.getsize(fullpath)/1024/1024, 1) or 0.1
        files[file] = size
    return render_template('common/filelist.html', files=files)

apps/front/__init__.py
from .views import bp
from . import hooks

apps/front/views.py
import re
import threading
from functools import reduce
from operator import add

import itsdangerous
from flask import (Blueprint, render_template,
                   views, session,
                   url_for, g, abort, redirect)

from exts import cache
from utils.recorder import record_thread_browse_log
from apps.front.forms import RegisterForm, LoginForm, ThreadForm, CommentForm, UpdateProfileForm, ChildCommentForm
from utils import restful, safeutils
from exts import db
from utils.mail import send_mail
from .models import FrontUser, GenderEnum, BoardManage
from ..models import Banner, Board, Thread, Comment, HlThread, ThreadLike, ThreadCollect, CommentLike
from ..cms.auth import front_login_auth
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import or_
from datetime import datetime
from sqlalchemy import func
import os, random, string
from qiniu import Auth, etag, put_file
from flask import request, jsonify
from werkzeug.utils import secure_filename
from config import QINIU_AK, QINIU_BUCKET, QINIU_SK, QINIU_DOMAIN
import config

bp = Blueprint('front', __name__)


@bp.app_errorhandler(404)
def handle_error(e):
    return render_template('front/404.html'), 404


@bp.app_template_filter(name='timedelta')
def time_delta(time):
    if isinstance(time, datetime):
        now = datetime.now()
        timestamp = (now - time).total_seconds()
        if timestamp < 60:
            return '刚刚'
        elif 60 <= timestamp < 60 * 60:
            minutes = timestamp / 60
            return '%s 分钟前' % int(minutes)
        elif 60 * 60 <= timestamp < 60 * 60 * 24:
            hours = timestamp / (60 * 60)
            return '%s小时前' % int(hours)
        elif 60 * 60 * 24 <= timestamp < 60 * 60 * 24 * 30:
            days = timestamp / (60 * 60 * 24)
            return '%s天前' % int(days)
        else:
            return time.strftime('%Y/%m/%d/ %H:%M')


@bp.route('/qiniuupload/', methods=["GET", "POST"])
def qiniuupload():
    if request.method == "POST":
        up = UpFile()
        f = request.files["avatar"]
        filename = os.path.join(config.USER_AVATARS, secure_filename(f.filename))
        f.save(filename)
        mime = filename.rsplit(".")[1]
        qiniu_url = up.upload_img(filename, mime)

        if qiniu_url:
            user = FrontUser.query.get(g.front_user.id)
            user.avatar = 'https://' + qiniu_url
            db.session.commit()
            up.notify("qiniu-fileup", "图片上传成功")
            return jsonify({'code': 200, 'message': ''})
        else:
            up.notify("qiniu-fileup", "图片上传失败")
            return jsonify({'code': 400, 'message': 'Internal Server Error'})


class UpFile(object):
    @staticmethod
    def random_name():
        return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(5))

    def upload_img(self, fn, sfx):
        key = self.random_name() + "." + sfx
        q = Auth(QINIU_AK, QINIU_SK)
        token = q.upload_token(QINIU_BUCKET, key, 3600)
        ret, info = put_file(token, key, fn)
        if (ret is not None) and ret['key'] == key and ret['hash'] == etag(fn):
            return QINIU_DOMAIN + key
        else:
            self.notify("qiniu-fileup", "上传七牛云失败")
            return False

    @staticmethod
    def notify(title, text):
        os.system("osascript -e 'display notification \"{}\" with title \"{}\"'".format(text, title))


@bp.route('/')
@cache.cached(timeout=60, query_string=True)
def index():
    banners = Banner.query.order_by(Banner.priority.desc()).limit(4)
    boards = Board.query.all()
    page = request.args.get(get_page_parameter(), type=int, default=1)
    filter_by = request.args.get('filter_by', type=str, default='most-newest')
    if filter_by not in ['most-newest', 'well-chosen', 'liked-most', 'commented-most', 'browsed-most']:
        filter_by = 'most-newest'
    bid = request.args.get('bid', type=int, default=None)
    threads = None
    if filter_by == 'most-newest':
        threads = Thread.query.order_by(Thread.create_time.desc())
    elif filter_by == 'well-chosen':
        threads = db.session.query(Thread).outerjoin(HlThread).order_by(HlThread.create_time.desc(),
                                                                        Thread.create_time.desc())
    elif filter_by == 'liked-most':
        threads = db.session.query(Thread). \
            outerjoin(ThreadLike). \
            group_by(Thread.id). \
            order_by(func.count(ThreadLike.thread_id).desc(), Thread.create_time.desc())
    elif filter_by == 'commented-most':
        threads = db.session.query(Thread). \
            outerjoin(Comment). \
            group_by(Thread.id). \
            order_by(func.count(Comment.thread_id).desc(), Thread.create_time.desc())
    elif filter_by == 'browsed-most':
        threads = Thread.query.order_by(Thread.browse_num.desc())
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    if bid:
        threads_obj = threads.filter(Thread.board_id == bid)
        threads = threads_obj.slice(start, end)
        total = threads_obj.count()
    else:
        threads = threads.slice(start, end)
        total = Thread.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total)
    recommend = Thread.query.outerjoin(ThreadLike).outerjoin(Comment).group_by(Thread.id).order_by(
        func.count(ThreadLike.thread_id).desc(), func.count(Comment.thread_id).desc()).limit(7)

    tl = Thread.query.join(ThreadLike).\
        group_by(Thread.author_id).\
        order_by(func.count(ThreadLike.id).desc()).\
        slice(0, 5)
    most_liked_user = FrontUser.query.join(Thread).join(ThreadLike).group_by(FrontUser.id).order_by(func.count(ThreadLike.id).desc())[:3]
    # most_liked_user = [item.author for item in tl]
    for user in most_liked_user:
        user_threads = Thread.query.filter_by(author=user)
        total_thread_likes = reduce(add, [len(thread.likes) for thread in user_threads])
        # print('total_thread_likes', total_thread_likes)
        setattr(user, 'total_liked_num', total_thread_likes)
        # for _ in most_liked_user:
        # [setattr(user, 'total_liked_num', ThreadLike.query.filter_by(user_id=user.id).count()) for user in most_liked_user]
    context = {
        'banners': banners,
        'boards': boards,
        'threads': threads,
        'pagination': pagination,
        'board_id': bid,
        'filter_by': filter_by,
        'recommend': recommend,
        'most_liked_user': most_liked_user
    }
    return render_template('front/index.html', **context)


@bp.route('/profile/<string:id>/')
@front_login_auth
def profile(id):
    user = FrontUser.query.get(id)
    if not user:
        abort(404)
    last_ptime = user.threads[0].create_time if user.threads else ''
    return render_template('front/profile.html', user=user, last_ptime=last_ptime)


@bp.route('/updateprofile/<string:id>/', methods=['get', 'post'])
@front_login_auth
def update_profile(id):
    if request.method == 'GET':
        managed_boards = ','.join([board_manager.board.name for board_manager in BoardManage.query.filter_by(manager_id=g.front_user.id).all()])
        return render_template('front/updateprofile.html', managed_boards=managed_boards)
    form = UpdateProfileForm(request.form)
    if form.validate():
        username = form.username.data
        email = form.email.data
        gender = GenderEnum(request.form.get('gender'))
        qq = request.form.get('qq')
        user = FrontUser.query.filter_by(id=id).first()
        if user.email != email and FrontUser.query.filter_by(email=email).first():
            return restful.params_error('此邮箱已存在')
        if user.username != username and FrontUser.query.filter_by(username=username).first():
            return restful.params_error('用户名已存在')
        user.username = username
        user.email = email
        user.gender = gender
        user.qq = qq
        db.session.commit()
        return restful.success()
    return restful.params_error(form.get_error())


@bp.route('/threadlist/<string:uid>/')
@front_login_auth
def threadlist(uid):
    user = FrontUser.query.get(uid)
    if not user:
        return restful.params_error('Unregisterd user')
    threads = Thread.query.filter_by(author_id=uid).order_by(Thread.create_time.desc()).all()
    context = dict(items=threads, user=user, title='帖子')
    return render_template('front/itemlist.html', **context)


@bp.route('/search/')
def search():
    kw = request.args.get('kw')
    if not kw:
        return redirect(url_for('front.index'))
    threads_obj = Thread.query.filter(
        or_(Thread.title.like('%' + kw + '%'), Thread.content.like('%' + kw + '%'))).order_by(Thread.create_time.desc())
    threads = threads_obj.all()
    thread_count = threads_obj.count()
    return render_template('front/search.html', threads=threads, thread_count=thread_count)


@bp.route('/logout/')
@front_login_auth
def log_out():
    session.clear()
    return redirect(url_for('front.login'))


@bp.route('/thread/', methods=['GET', 'POST'])
@front_login_auth
def post():
    if request.method == 'GET':
        tid = request.args.get('tid')
        thread = None
        if tid:
            thread = Thread.query.get(tid)
        boards = Board.query.all()
        context = {
            'boards': boards,
            'thread': thread
        }
        return render_template('front/post.html', **context)
    else:
        form = ThreadForm(request.form)
        if form.validate():
            tid = request.form.get('tid')
            if tid:
                thread = Thread.query.get(tid)
                thread.title = form.title.data
                thread.content = form.content.data
                thread.board_id = form.board_id.data
                thread.is_edited = True
            else:
                title = form.title.data
                content = form.content.data
                board_id = form.board_id.data

templates/front/index_base.html
<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='front/css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='common/favicon.ico') }}" type="image/x-icon"/>
    <script src="{{ url_for('static', filename='front/js/jquery-1.11.0.min.js') }}"></script>
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %}CodingLife</title>
    <link type=text/css rel="stylesheet" href="{{ url_for('static', filename='front/css/index_base.css') }}">
    {% block head %}{% endblock %}

</head>
<body>
<div class="con">
    <div class="htmleaf-container">
        <nav class="navbar nb navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    {#                    <a class="navbar-brand" href="/">CodingLife</a>#}
                    <a class="navbar-brand" href="/" style="padding:6px 10px 10px 10px">
                        <img style="height: 39px;" alt="Brand" src="{{ url_for('static', filename="common/nav_logo.png") }}">
                    </a>
                    <button type="button" class="navbar-toggle navbar-toggle-border collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar icon-bar-border"></span>
                        <span class="icon-bar icon-bar-border"></span>
                        <span class="icon-bar icon-bar-border"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
                    </ul>

                    <form class="form-inline navbar-form navbar-left">
                      <div class="form-group">
                        <div class="input-group">
                          <input type="text" class="form-control" id="kw" placeholder="请输入关键字">
                          <div class="input-group-addon"><span id="search" class="glyphicon glyphicon-search"></span></div>
                        </div>
                      </div>
                    </form>
                    <script type="text/javascript">
                            $(function () {
                                $('#search').click(function () {
                                    var kw = $("#kw").val();
                                    if (!kw) {
                                        return
                                    }
                                    window.location.href = "/search/?kw=" + kw;
                                });
                            });
                    </script>


                    <ul class="nav navbar-nav navbar-right">
                        {% if g.front_user %}
                            <li class="active"><a href="/thread">发贴</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true" aria-expanded="false">{{ g.front_user.username }}<span
                                        class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('front.update_profile', id=g.front_user.id) }}">修改资料</a>
                                    </li>
                                    <li><a href="{{ url_for('front.threadlist', uid=g.front_user.id) }}">我的帖子</a>
                                    </li>
                                    <li><a href="{{ url_for('front.collectlist', uid=g.front_user.id) }}">我的收藏</a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('front.reset_password', email=g.front_user.email) }}">修改密码</a>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for('front.log_out') }}">退出登录</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{{ url_for('front.register') }}">注册</a></li>
                            <li><a href="{{ url_for('front.login') }}">登录</a></li>
                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>

    <div class="main-container">
        {% block body %}{% endblock %}
    </div>
    <footer>
        <nav class="navbar nb">
            <p>Powered by: <i>Gorgine</i>&nbsp&nbspEmail: <i>8@hugj.cn</i></p>
            <p>© 2019 CodingLife&nbsp
                <img src="{{ url_for('static', filename="front/images/footerlogo.png") }}" data-was-processed="true">
                <a id="internet-content-provider" rel="nofollow" href="//www.beian.miit.gov.cn" target="_blank">湘ICP备19007920号</a>
            </p>
        </nav>
    </footer>

</div>
</body>
</html>

templates/front/login.html
{% extends 'front/reg_log_base.html' %}
{% block title %}用户登录{% endblock %}
{% block head %}
    <script src="{{ static('front/js/login.js') }}"></script>
{% endblock %}

{% block h2 %}用户登录{% endblock %}

{% block form_box %}
    <form:form action="/login" method="post" role="form">
        <div class="form-group">
            <input type="text" class="form-control" name="account" placeholder="请输入用户名/邮箱">
    </div>

    <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="请输入密码">
    <div style="float: left" class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住密码
        </label>
    </div>
    </div>

    <div class="form-group">
            <input id="login" type="submit" class="btn btn-warning btn-block" value="立即登录">
    </div>

    <div class="form-group">
        <a href="{{ url_for('front.reset_password') }}" class="pull-left">找回密码</a>
        <a href="{{ url_for('front.register') }}" class="pull-right">立即注册</a>
    </div>
    </form:form>
{% endblock %}

templates/front/post.html
{% extends 'front/index_base.html' %}

{% block title %}发布帖子 - {% endblock %}

{% block head %}
    <script type="text/javascript" src="{{ url_for('static', filename="ueditor/ueditor.config.js") }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename="ueditor/ueditor.all.js") }}"></script>
    <script src="{{ url_for('static', filename="front/js/post.js") }}"></script>
    <style>
        body {
            margin: 0 auto;
        }

        .publish {
            float: right;
        }
    </style>
{% endblock %}

{% block body %}
    <div id="content" hidden>{{ thread.content | safe }}</div>
    <div id="title" hidden>{{ thread.title }}</div>
    <div id="board" hidden>{{ thread.board_id }}</div>
    <div class="post-container col-sm-8 col-sm-offset-2">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" class="form-control" name="title">
            </div>
        </div>

        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">板块</span>
                <select name="board" id="" class="form-control">
                    {% for board in boards %}
                        <option value="{{ board.id }}">{{ board.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-group editor">
            <script id="container" name="content" type="text/plain" style="height: 320px"></script>
        </div>


        <div class="form-group publish">
            <button class="btn btn-warning" id="publish-btn" tid="{{ thread.id }}">发布</button>
        </div>
    </div>

{% endblock %}

templates/front/profile.html
{% extends 'front/index_base.html' %}

{% block title %}{{ user.username }} - {% endblock %}

{% block head %}
    <link type=text/css rel="stylesheet" href="{{ url_for('static', filename="front/css/profile.css") }}">
    <script src="{{ url_for('static', filename="front/js/profile.js") }}"></script>
{% endblock %}

{% block body %}
    <div class="body-container col-sm-8 col-sm-offset-2">
        <h2>TA的信息</h2>
        <div class="avatar-username">
            <img id="avatar" src="{{ url_for('avatar', text=user.username) }}" alt="" style="border-radius: 50%">
        <span class="username"><b>{{ user.username }}</b></span>
        </div>
        <table class="table table-bordered table-striped table-style">
            <tbody>

            <tr class="">
                <td>邮箱</td>
                <td>{{ user.email or '' }}</td>
            </tr>

            <tr class="">
                <td>QQ</td>
                <td>{{ user.qq or '' }}</td>
            </tr>
            <tr class="">
                <td>性别</td>
                <td>{{ user.gender.value or '' }}</td>
            </tr>
            <tr class="">
                <td>发帖数</td>
                <td>{{ user.threads | length }}</td>
            </tr>

            <tr class="">
                <td>最近发帖</td>
                <td>{{ last_ptime }}</td>
            </tr>
            <tr class="">
                <td>TA的帖子</td>
                <td><a href="{{ url_for('front.threadlist', uid=user.id) }}">查看帖子</a></td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/front/register.html
{% extends 'front/reg_log_base.html' %}
{% block title %}用户注册{% endblock %}
{% block head %}
    <script src="{{ static('front/js/register.js') }}"></script>
    <style>
        .capcha-addon {
            padding: 0;
            overflow: hidden;
        }

        .capcha-img {
            width: 94px;
            height: 32px;
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block h2 %}用户注册{% endblock %}

{% block form_box %}
    <form:form action="/login" method="post" role="form">
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="email" placeholder="您的邮箱">
                <span class="input-group-btn">
                        <button id="send_sms" class="btn btn-default">发送验证码</button>
            </span>
            </div>
        </div>

        <div class="form-group">
            <input type="text" class="form-control" name="captcha" placeholder="邮箱验证码">
        </div>

        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="用户名">
        </div>

        <div class="form-group">
            <input type="password" class="form-control" name="password1" placeholder="密码">
        </div>

        <div class="form-group">
            <input type="password" class="form-control" name="password2" placeholder="确认密码">
        </div>

        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                <span class="input-group-addon capcha-addon">
                        <img class="capcha-img" id="capcha-img" src="{{ url_for('common.captcha') }}" alt="">
                    </span>
            </div>
        </div>
        {% if next_to %}
            <span id="next_to" hidden="hidden">{{ next_to }}</span>
        {% endif %}
        <div class="form-group">
            <button class="btn btn-warning btn-block" id="sub-btn">立即注册</button>
        </div>

        <div class="form-group">
            <a href="{{ url_for('front.index') }}" class="pull-left">回到首页</a>
            <a href="{{ url_for('front.login') }}" class="pull-right">已有账号，立即登录</a>
        </div>
    </form:form>
{% endblock %}