apps/common/__init__.py
from .views import bp

apps/common/views.py
from flask import Blueprint, make_response, request, render_template, jsonify, send_from_directory
from utils.captcha import Captcha
from io import BytesIO
from utils.sms import send_sms
from utils import restful
from exts import cache
from apps.front.forms import SendSMSForm
from werkzeug.utils import secure_filename
import string
import random
import config
import os

bp = Blueprint('common', __name__)


@bp.route('/captcha/')
def captcha():
    text, image = Captcha.gene_graph_captcha()
    text = text.lower()
    io = BytesIO()
    image.save(io, 'png')
    io.seek(0)
    resp = make_response(io.read())
    resp.content_type = 'image/png'
    cache.set(text, text, timeout=90)
    # print(text)
    return resp


@bp.route('/verify_captcha/<code>/')
def verify_captcha(code):
    # code = request.args.get('code')
    code = code.lower()
    flag = True if cache.get(code) else False
    return jsonify({'code': 200, 'verified': flag})


@bp.route('/sms_captcha/', methods=["POST"])
def sms_captcha():
    form = SendSMSForm(request.form)
    if form.validate():
        phone = form.phone.data
        captcha = "".join(random.sample(list(string.digits), 6))
        try:
            send_sms(phone, captcha)
            cache.set(phone, captcha)
            print(captcha)
            return restful.success('发送验证码成功')
        except:
            resp = send_sms(phone, captcha)
            print(captcha)
            return restful.server_error(resp['msg'])
    else:
        return restful.params_error(form.get_error())


@bp.route('/upload/', methods=['get', 'post'])
def upload():
    if request.method == 'GET':
        return render_template('common/upload.html')
    if not os.path.dirname(config.UPLOAD_FOLDER):
        os.mkdir(config.UPLOAD_FOLDER)
    f = request.files.get('myfile')
    if not f:
        return jsonify({'code': 400, 'message': 'no file'})
    filename = secure_filename(f.filename)
    filepath = os.path.join(config.UPLOAD_FOLDER, filename)
    f.save(filepath)
    return jsonify({'code': 200, 'message': 'upload successfully'})


@bp.route('/download/<path:filename>/')
def download(filename):
    filedir = config.UPLOAD_FOLDER
    return send_from_directory(filedir, filename, as_attachment=True)


@bp.route('/filelist/')
def filelist():
    files = {}
    for file in os.listdir(config.UPLOAD_FOLDER):
        fullpath = os.path.join(config.UPLOAD_FOLDER, file)
        size = round(os.path.getsize(fullpath)/1024/1024, 1) or 0.1
        files[file] = size
    return render_template('common/filelist.html', files=files)

templates/common/_heads.html
{% from 'common/_macros.html' import static %}
<meta name="csrf-token" content="{{ csrf_token() }}">
<script src="{{ url_for('static', filename="common/bootstrap/jquery-3.4.1.min.js")}}"></script>
<link type=text/css href="{{ url_for('static', filename="common/bootstrap/css/bootstrap.min.css")}}" rel="stylesheet">
<script src="{{ url_for('static', filename="common/bootstrap/js/bootstrap.min.js")}}"></script>
<link type=text/css rel="stylesheet" href="{{ static('common/sweetalertv/sweetalert.css') }}">
<script src="{{ static('common/sweetalertv/sweetalert.min.js') }}"></script>
<script src="{{ static('common/sweetalertv/xtalert.js') }}"></script>
<script src="{{ static('common/zlajax.js') }}"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y4KE6JWDR6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y4KE6JWDR6');
</script>

templates/common/_macros.html
{% macro static(filename) -%}
    {{ url_for('static', filename=filename) }}
{%- endmacro %}

templates/common/filelist.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="icon" href="{{ url_for('static', filename='common/favicon.ico') }}" type="image/x-icon">
  <title>CodingLife - GJYun</title>
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<body>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>文件</th>
            <th>大小</th>
            <th>下载</th>
        </tr>
    </thead>
    <tbody>
        {% for name, size in files.items() %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ name }}</td>
                <td>{{ size }}M</td>
                <td><a href="{{ url_for('common.download', filename=name) }}">点击下载</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/common/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{{ url_for('static', filename='common/favicon.ico') }}" type="image/x-icon">
    <title>CodingLife - Upload</title>
</head>
<body>
<form id="form1" method="post" action="" enctype="multipart/form-data">
    <div>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input id="File1" type="file" name="myfile"/>  <!--后台代码中获取文件是通过form的name来标识的-->
        <input type="submit">
    </div>
</form>
</body>
</html>