apps/cms/models.py
from exts import db
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime


class CMSPermission(object):
    ALL_PERMISSION = 0b11111111
    VISITOR        = 0b00000001
    POSTER         = 0b00000010
    COMMENTER      = 0b00000100
    BOARDER        = 0b00001000
    FRONTUSER      = 0b00010000
    CMSUSER        = 0b00100000
    BOARD_MANAGER  = 0b01000000


cms_role_user = db.Table(
    'cms_role_user',
    db.Column('role_id', db.Integer, db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('cms_user.id'), primary_key=True)
)


class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    permission = db.Column(db.Integer, default=CMSPermission.VISITOR)
    desc = db.Column(db.String(200), nullable=True)
    create_time = db.Column(db.DateTime, default=datetime.now)

    users = db.relationship('CMSUser', secondary='cms_role_user', backref='roles')


class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    create_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permission = 0
        for role in self.roles:
            all_permission |= role.permission
        return all_permission

    def has_permission(self, permission):
        return permission == self.permissions & permission

    def is_developer(self):
        return self.has_permission(CMSPermission.ALL_PERMISSION)

apps/cms/forms.py
from wtforms import StringField, IntegerField, Form, ValidationError
from wtforms.validators import Length, InputRequired, Email, EqualTo
from ..forms import BaseForm
from exts import cache
from apps.cms.models import CMSUser
from ..front.models import FrontUser, BoardManage


class LoginForm(BaseForm):
    email = StringField(validators=[Email()])
    password = StringField(validators=[Length(6, 20, message='请输入长度为6-20位的密码')])
    remember = IntegerField()


class ResetPwdForm(BaseForm):
    old_pwd = StringField(validators=[Length(6, 20, message='请输入长度为6-20位的密码')])
    new_pwd = StringField(validators=[Length(6, 20, message='请输入长度为6-20位的密码')])
    new_pwd_repeat = StringField(validators=[EqualTo('new_pwd', message='两次密码输入不一致')])


class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱')])
    captcha = StringField(validators=[Length(6, 6, message='请输入长度为6位的验证码')])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        if not captcha or captcha != cache.get(email):
            raise ValidationError('验证码不正确或已过期')

    def validate_email(self, field):
        email = field.data
        user = CMSUser.query.filter_by(email=email).first()
        if user:
            raise ValidationError('该邮箱已绑定其他账号')


class BannerForm(BaseForm):
    name = StringField(validators=[InputRequired(message="请输入轮播图名称")])
    img_url = StringField(validators=[InputRequired(message="请输入图片链接")])
    link_url = StringField(validators=[InputRequired(message="请输入跳转链接")])
    priority = IntegerField(validators=[InputRequired(message="请输入权重")])


class BannerModForm(BannerForm):
    bid = IntegerField(validators=[InputRequired(message='请输入轮播图ID')])


class BannerDelForm(BaseForm):
    bid = IntegerField(validators=[InputRequired(message='请输入轮播图ID')])


class BoardForm(BaseForm):
    name = StringField(validators=[InputRequired('请输入板块名称')])


class BoardModForm(BoardForm):
    bdid = IntegerField(validators=[InputRequired(message='请输入板块ID')])


class BoardManageForm(BaseForm):
    bdid = IntegerField(validators=[InputRequired(message='请输入板块ID')])
    username = StringField(validators=[InputRequired('请输入用户名称')])

    def validate_username(self, field):
        user = FrontUser.query.filter_by(username=field.data).first()
        if not user:
            raise ValidationError('用户不存在')

apps/cms/__init__.py
from .views import bp
import apps.cms.hooks

apps/cms/auth.py
from functools import wraps
from flask import session, redirect, url_for, g
from config import CMS_USER_ID, FRONT_USER_ID


def login_auth(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if session.get(CMS_USER_ID):
            return func(*args, **kwargs)
        else:
            return redirect(url_for('cms.login'))
    return wrapper


def access_auth(permission):
    def outter(func):
        @wraps(func)
        def inner(*args, **kwargs):
            if g.cms_user.has_permission(permission):
                return func(*args, **kwargs)
            return redirect(url_for('cms.index'))
        return inner
    return outter


def front_login_auth(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if session.get('FRONT_USER_ID'):
            return func(*args, **kwargs)
        else:
            return redirect(url_for('front.login'))
    return wrapper

apps/cms/views.py
import random
import string
import threading

from flask import Blueprint, views, render_template, request, session, redirect, url_for, g, jsonify
from flask_mail import Message
from flask_paginate import Pagination, get_page_parameter

from apps.front.models import FrontUser, BoardManage
from config import CMS_USER_ID
from exts import db
from utils import restful
from utils.mail import mail_and_cache
from .auth import login_auth, access_auth
from .forms import (
    LoginForm, ResetPwdForm, ResetEmailForm,
    BannerForm, BannerModForm, BannerDelForm,
    BoardForm, BoardModForm, BoardManageForm,
)

from .models import CMSUser, CMSPermission, CMSRole
from ..models import Banner, Board, Thread, Comment, HlThread

bp = Blueprint('cms', __name__, url_prefix='/cms')


@bp.route('/')
@login_auth
def index():
    return render_template('cms/cms_index.html')


@bp.route('/profile/')
@login_auth
def get_profile():
    return render_template('cms/profile.html')


@bp.route('/logout/')
@login_auth
def logout():
    session.clear()
    return redirect(url_for('cms.login'))


@bp.route('/sendcaptcha/')
def send_captcha():
    email = request.args.get('email')
    import re
    if not re.match(r'^[a-z0-9-_.]+@([a-z0-9]+.)+[a-z]+$', email):
        return restful.params_error('请输入正确格式的邮箱')
    captcha = list(string.ascii_letters)
    captcha.extend(map(lambda x: str(x), list(range(10))))
    captcha = random.sample(captcha, 6)
    captcha = "".join(captcha)
    msg = Message('CodingLife', recipients=[email], body='您的验证码是：%s' % captcha)
    threading.Thread(target=mail_and_cache, args=(email, msg, captcha)).run()
    return restful.success(message='发送邮件成功')


@bp.route('/banner/')
@login_auth
def banner_manage():
    banners = Banner.query.order_by(Banner.priority.desc()).all()
    return render_template('cms/banner.html', banners=banners)


@bp.route('/add_banner/', methods=['POST'])
@login_auth
def add_banner():
    form = BannerForm(request.form)
    print(request.form)
    if form.validate():
        name = form.name.data
        img_url = form.img_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = Banner(name=name, img_url=img_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())


@bp.route('/mod_banner/', methods=['POST'])
@login_auth
def mod_banner():
    form = BannerModForm(request.form)
    if form.validate():
        name = form.name.data
        img_url = form.img_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        bid = form.bid.data
        banner = Banner.query.get(bid)
        if banner:
            banner.name = name
            banner.img_url = img_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error("此轮播图不存在")
    else:
        return restful.params_error(form.get_error())


@bp.route('/del_banner/', methods=['POST'])
@login_auth
def del_banner():
    form = BannerDelForm(request.form)
    if form.validate():
        bid = form.bid.data
        print(bid)
        banner = Banner.query.get(bid)
        if banner:
            db.session.delete(banner)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('此轮播图不存在')
    else:
        return restful.params_error(form.get_error())


@bp.route('/thread/')
@login_auth
@access_auth(CMSPermission.POSTER)
def thread_manage():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page-1)*10
    end = (page-1)*10+10
    threads = Thread.query.order_by(Thread.create_time.desc()).slice(start, end)
    pagination = Pagination(bs_version=3, page=page, total=Thread.query.count())
    return render_template('cms/thread.html', threads=threads, pagination=pagination)


@bp.route('/hl_thread/', methods=['POST'])
@login_auth
def hl_thread():
    thread_id = request.form.get('thread_id')
    if not thread_id:
        return restful.params_error('请传入帖子ID')
    thread = Thread.query.get(thread_id)
    if not thread:
        return restful.params_error('此帖子不存在')
    hlthread = HlThread(thread_id=thread_id)
    db.session.add(hlthread)
    db.session.commit()
    return restful.success()


@bp.route('/dishl_thread/', methods=['POST'])
@login_auth
def dishl_thread():
    thread_id = request.form.get('thread_id')
    if not thread_id:
        return restful.params_error('请传入帖子ID')
    thread = Thread.query.get(thread_id)
    if not thread:
        return restful.params_error('此帖子不存在')
    hlthread = HlThread.query.filter_by(thread_id=thread_id).first()
    db.session.delete(hlthread)
    db.session.commit()
    return restful.success()


@bp.route('/del_thread/', methods=['POST'])
@login_auth
def del_thread():
    thread_id = request.form.get('thread_id')
    if not thread_id:
        return restful.params_error('请传入帖子ID')
    thread = Thread.query.get(thread_id)
    if not thread:
        return restful.params_error('此帖子不存在')
    db.session.delete(thread)
    db.session.commit()
    return restful.success()


@bp.route('/comment/')
@login_auth
@access_auth(CMSPermission.COMMENTER)
def comment_manage():
    comments = Comment.query.order_by(Comment.create_time.desc()).all()
    return render_template('cms/comment.html', comments=comments)


@bp.route('/del_comment/', methods=['POST'])
@login_auth
def del_comment():
    comment_id = request.form.get('comment_id')
    if not comment_id:
        return restful.params_error('请传入评论ID')
    comment = Comment.query.get(comment_id)
    if not comment:
        return restful.params_error('此评论不存在')
    db.session.delete(comment)
    db.session.commit()
    return restful.success()


@bp.route('/board/')
@login_auth
@access_auth(CMSPermission.BOARDER)
def board_manage():
    boards = Board.query.all()
    return render_template('cms/board.html', boards=boards)


@bp.route('/add_board/', methods=['POST'])
@login_auth
@access_auth(CMSPermission.BOARDER)
def add_board():
    form = BoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = Board(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())


@bp.route('/mod_board/', methods=['POST'])
@login_auth
@access_auth(CMSPermission.BOARDER)
def mod_board():
    form = BoardModForm(request.form)
    if form.validate():
        bdid = form.bdid.data
        name = form.name.data
        board = Board.query.get(bdid)
        if not board:
            return restful.params_error('此板块不存在')
        board.name = name
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())


@bp.route('/del_board/', methods=['POST'])
@login_auth
@access_auth(CMSPermission.BOARDER)
def del_board():
    bdid = request.form.get('bdid')
    if not bdid:
        return restful.params_error('请传入板块ID')
    board = Board.query.get(bdid)
    if not board:
        return restful.params_error('此板块不存在')
    db.session.delete(board)
    db.session.commit()
    return restful.success()


@bp.route('/fuser/')
@login_auth
@access_auth(CMSPermission.FRONTUSER)
def fuser_manage():
    users = FrontUser.query.all()
    return render_template('cms/fuser.html', users=users)


@bp.route('/del_fuser/')
@login_auth
def del_fuser():
    uid = request.args.get('uid')
    if not uid:
        return restful.params_error('请传入用户ID')
    user = FrontUser.query.get(uid)
    if not user:
        return get_page_parameter('用户不存在')
    db.session.delete(user)
    db.session.commit()
    return restful.success()


@bp.route('/buser/', methods=['GET', 'DELETE', 'PUT', 'POST'])
@login_auth
@access_auth(CMSPermission.CMSUSER)
def buser_manage():
    if request.method == 'GET':
        cms_users = CMSUser.query.all()
        cms_roles = CMSRole.query.all()
        for user in cms_users:
            setattr(user, 'role', ','.join([role.name for role in user.roles]))
        return render_template('cms/buser.html', users=cms_users, cms_roles=cms_roles)
    elif request.method == 'DELETE':
        uid = request.args.get('uid')
        cms_user = CMSUser.query.get(uid)
        print('cms_user', cms_user)
        db.session.delete(cms_user)
        db.session.commit()
        return restful.success()
    elif request.method == 'PUT':
        uid = request.args.get('uid')
        role_id = request.args.get('role_id')
        cms_user = CMSUser.query.get(uid)
        role = CMSRole.query.get(role_id)
        cms_user.roles = [role]
        db.session.commit()
        return restful.success()
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        role_id = request.form.get('role_id')
        role = CMSRole.query.get(role_id)
        print('role', role)
        user = CMSUser(username=username, password=password, email=email)
        role.users.append(user)
        db.session.add(user)
        db.session.commit()
        return restful.success()


@bp.route('/board_manager/')
@login_auth
@access_auth(CMSPermission.BOARD_MANAGER)
def board_manager_manage():
    # board_manages = BoardManage.query.all()
    boards = Board.query.all()
    for board in boards:
        board.__setattr__('board_manages', [ (board_manager.manager.username,  board_manager.id) for board_manager in board.board_managers])
    return render_template('cms/board_manager.html', boards=boards)


@bp.route('/board_manager/', methods=['POST'])
@login_auth
@access_auth(CMSPermission.BOARD_MANAGER)
def add_board_manager():
    form = BoardManageForm(request.form)
    if form.validate():

templates/cms/banner.html
{% extends 'cms/base.html' %}
{% block title %}
    轮播管理
{% endblock %}
{% block head %}
    <script src="{{ static('cms/js/banner.js') }}"></script>
    <style>.modal-backdrop {
        z-index: 0;
    }</style>
    <style type="text/css">
        .table {
            table-layout: fixed;
        }
        .table tbody tr td {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
    </style>
{% endblock %}
{% block page_title %}
    轮播管理
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" id="banner-add-btn" data-toggle="modal" data-target="#banner_modal">添加轮播
        </button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for banner in banners %}
            <tr bid="{{ banner.id }}" bname="{{ banner.name }}" bimg_url="{{ banner.img_url }}"
                blink_url="{{ banner.link_url }}" bpriority="{{ banner.priority }}">
                <td>{{ banner.name }}</td>
                <td><a href="{{ banner.img_url }}">{{ banner.img_url }}</a></td>
                <td><a href="{{ banner.link_url }}">{{ banner.link_url }}</a></td>
                <td>{{ banner.priority }}</td>
                <td>{{ banner.create_time }}</td>
                <td>
                    <button class="btn btn-success modify-btn btn-xs" data-toggle="modal" data-target="#banner_modal">
                        修改
                    </button>
                    <button class="btn btn-danger del-btn btn-xs">删除</button>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>


    <!-- Modal -->

    <div class="modal fade" id="banner_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">
                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">名称</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">图片</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="img_url">
                            </div>
                            <button class="btn btn-info col-sm-2">上传</button>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">跳转</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="link_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">权重</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="priority">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="save">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/base.html
{% from 'common/_macros.html' import static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %} - CodingLife</title>
    <link type=text/css rel="stylesheet" href="{{ static('cms/css/cms_base.css') }}">
    <meta name=”viewport” content=”width=device-width, initial-scale=1″ />
    <script src="{{ static('cms/js/cms_base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    {% set user = g.cms_user %}
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CodingLife后台管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.get_profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.get_profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>
                  <li class="nav-group banner-manage"><a href="{{ url_for('cms.banner_manage') }}">轮播管理</a></li>
                  {% if user.has_permission(CMSPermission.POSTER) %}
                      <li class="nav-group post-manage"><a href="{{ url_for('cms.thread_manage') }}">帖子管理</a></li>
                  {% endif %}
                  {% if user.has_permission(CMSPermission.COMMENTER) %}
                      <li class="comments-manage"><a href="{{ url_for('cms.comment_manage') }}">评论管理</a></li>
                  {% endif %}
                  {% if user.has_permission(CMSPermission.BOARDER) %}
                      <li class="board-manage"><a href="{{ url_for('cms.board_manage') }}">板块管理</a></li>
                  {% endif %}
                  {% if user.has_permission(CMSPermission.FRONTUSER) %}
                      <li class="nav-group user-manage"><a href="{{ url_for('cms.fuser_manage') }}">用户管理</a></li>
                  {% endif %}
                  {% if user.has_permission(CMSPermission.CMSUSER) %}
                      <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.buser_manage') }}">CMS用户管理</a></li>
                  {% endif %}

                  {% if user.has_permission(CMSPermission.BOARD_MANAGER) %}
                      <li class="board-manager-manage"><a href="{{ url_for('cms.board_manager_manage') }}">版主管理</a></li>
                  {% endif %}

            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main side-bar">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/board.html
{% extends 'cms/base.html' %}
{% block title %}
    板块管理
{% endblock %}
{% block page_title %}
    板块管理
{% endblock %}
{% block head %}
    <script src="{{ url_for('static', filename="cms/js/board.js") }}"></script>
{% endblock %}
{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" id="add-board">添加板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>板块名称</th>
                <th>帖子数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr>
                    <td class="border-name">{{ board.name }}</td>
                    <td>{{ board.threads | length }}</td>
                    <td>{{ board.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs modify-board" bdid="{{ board.id }}">修改</button>
                        <button class="btn btn-danger btn-xs delete-board" bdid="{{ board.id }}">删除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/cms/board_manager.html
{% extends 'cms/base.html' %}
{% block title %}
    版主管理
{% endblock %}
{% block head %}
    <style>.modal-backdrop{z-index:0;}</style>
    <script src="{{ url_for('static', filename='cms/js/mod_board_manager.js') }}"></script>
{% endblock %}
{% block page_title %}
    版主管理
{% endblock %}
{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>板块</th>
            <th>版主</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <style>
            {#.board-manage:hover {#}
            {#    background-color: #d9534f;#}
            {#    cursor: pointer;#}
            {#    padding: 5px;#}
            {#    zoom: 1.1;#}
            {#    border-radius: 3px;#}
            {#}#}
        </style>
        {% for board in boards %}
            <tr>
                <td>{{ board.name }}</td>
                <td>
                    {% for board_manage in board.board_manages %}
                        <span bmid="{{ board_manage[1] }}" class="board-manager-name">{{ board_manage[0] }}

                        </span>
                    {% endfor %}

                </td>
                <td>
                    <button bdid="{{ board.id }}" bdname="{{ board.name }}" class="btn btn-success board-manager-add-btn" data-toggle="modal" data-target="#board_manager_manage_modal">添加版主</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <!-- Modal -->

    <div class="modal fade" id="board_manager_manage_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加版主</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">
                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">用户名</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="username">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label col-sm-2">所属板块</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="board">
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary save-board-manage-btn">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/base.html' %}
{% block title %}
    后台首页
{% endblock %}
{% block page_title %}
    <h2>亲爱的{{ g.cms_user.username }}，欢迎来到CodingLife后台管理系统！</h2>
{% endblock %}

templates/cms/fuser.html
{% extends 'cms/base.html' %}
{% block title %}
    前台用户管理
{% endblock %}
{% block head %}
    <script src="{{ url_for('static', filename='cms/js/del_fuser.js') }}"></script>
{% endblock %}
{% block page_title %}
    前台用户管理
{% endblock %}
{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>用户ID</th>
            <th>用户名</th>
            <th>邮  箱</th>
            <th>发帖数</th>
            <th>评论数</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.threads | length }}</td>
                <td>{{ user.comments | length }}</td>
                <td>
                    <button user_id="{{ user.id }}" class="btn btn-danger comment-del-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/role.html
{% extends 'cms/base.html' %}
{% block title %}
    组管理
{% endblock %}
{% block page_title %}
    组用户管理
{% endblock %}
{% block main_content %}
    组用户管理界面
{% endblock %}